id = "tokyo-night"
name = "Tokyo Night Themes"
version = "0.1.3"
schema_version = 1
authors = ["ssaunderss <austinsaunders@me.com>"]
description = "Tokyo Night Themes"
repository = "https://github.com/ssaunderss/zed-tokyo-night"
